name: optika
description: "учебка."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  http: 1.3.0
  # Для сериализации JSON в модели, можно использовать 'json_serializable'
  json_annotation: ^4.4.0
  # Поддержка json_serializable (генерация кодов)
  build_runner: ^2.3.3
  json_serializable: ^6.1.4
  provider: ^6.1.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

